In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from urllib.parse import unquote

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/shashwatwork/dataco-smart-supply-chain-for-big-data-analysis/tokenized_access_logs.csv
/kaggle/input/datasets/shashwatwork/dataco-smart-supply-chain-for-big-data-analysis/DataCoSupplyChainDataset.csv
/kaggle/input/datasets/shashwatwork/dataco-smart-supply-chain-for-big-data-analysis/DescriptionDataCoSupplyChain.csv

In [2]:
df=pd.read_csv("/kaggle/input/datasets/shashwatwork/dataco-smart-supply-chain-for-big-data-analysis/tokenized_access_logs.csv")

In [3]:
df.columns

Index(['Product', 'Category', 'Date', 'Month', 'Hour', 'Department', 'ip',
       'url'],
      dtype='object')

In [4]:
print(os.listdir("/kaggle/input/datasets"))

['shashwatwork']

In [5]:
df1=pd.read_csv("/kaggle/input/datasets/shashwatwork/dataco-smart-supply-chain-for-big-data-analysis/DataCoSupplyChainDataset.csv",encoding='latin1')

In [6]:
df1.columns

Index(['Type', 'Days for shipping (real)', 'Days for shipment (scheduled)',
       'Benefit per order', 'Sales per customer', 'Delivery Status',
       'Late_delivery_risk', 'Category Id', 'Category Name', 'Customer City',
       'Customer Country', 'Customer Email', 'Customer Fname', 'Customer Id',
       'Customer Lname', 'Customer Password', 'Customer Segment',
       'Customer State', 'Customer Street', 'Customer Zipcode',
       'Department Id', 'Department Name', 'Latitude', 'Longitude', 'Market',
       'Order City', 'Order Country', 'Order Customer Id',
       'order date (DateOrders)', 'Order Id', 'Order Item Cardprod Id',
       'Order Item Discount', 'Order Item Discount Rate', 'Order Item Id',
       'Order Item Product Price', 'Order Item Profit Ratio',
       'Order Item Quantity', 'Sales', 'Order Item Total',
       'Order Profit Per Order', 'Order Region', 'Order State', 'Order Status',
       'Order Zipcode', 'Product Card Id', 'Product Category Id',
       'Product Description', 'Product Image', 'Product Name', 'Product Price',
       'Product Status', 'shipping date (DateOrders)', 'Shipping Mode'],
      dtype='object')

In [7]:
df2=pd.read_csv("/kaggle/input/datasets/shashwatwork/dataco-smart-supply-chain-for-big-data-analysis/DescriptionDataCoSupplyChain.csv",encoding='latin1')

In [8]:
df2.columns

Index(['FIELDS', 'DESCRIPTION'], dtype='object')

In [9]:
df.shape

(469977, 8)

In [10]:
df2.shape

(52, 2)

In [11]:
df1.shape

(180519, 53)

In [12]:
df.columns.dtype

dtype('O')

In [13]:
df1.head()

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2/3/2018 22:56,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 11:24,Standard Class

In [14]:
df1['Sales per customer'].describe()

count    180519.000000
mean        183.107609
std         120.043670
min           7.490000
25%         104.379997
50%         163.990005
75%         247.399994
max        1939.989990
Name: Sales per customer, dtype: float64

In [15]:
len(df1)
df1['Sales per customer'].isnull().sum()

np.int64(0)

In [16]:
df1['Sales per customer'].sort_values(ascending=False).head(10)
#comparing the max values of top 10 with the median above for the column,
#mass percentage falls under median 163 but the top values are outliers|

175116    1939.98999
83214     1919.98999
63990     1899.98999
82117     1889.98999
173436    1859.98999
82130     1819.98999
48281     1799.98999
13343     1759.98999
148405    1739.98999
148406    1699.98999
Name: Sales per customer, dtype: float64

In [17]:
df1.columns.dtype

dtype('O')

In [18]:
df1.head(10)

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2/3/2018 22:56,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 11:24,Standard Class
5,TRANSFER,6,4,18.580000,294.980011,Shipping canceled,0,73,Sporting Goods,Tonawanda,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/19/2018 11:03,Standard Class
6,DEBIT,2,1,95.180000,288.420013,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 10:42,First Class
7,TRANSFER,2,1,68.430000,285.140015,Late delivery,1,73,Sporting Goods,Miami,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 10:21,First Class
8,CASH,3,2,133.720001,278.589996,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/16/2018 10:00,Second Class
9,CASH,2,1,132.149994,275.309998,Late delivery,1,73,Sporting Goods,San Ramon,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 9:39,First Class

In [19]:
df1.columns=df1.columns.str.lower().str.replace(' ','_').str.replace('-','_')
#fixing any whitespace with underscore so no issues occure in sql

In [20]:
df1=df1.dropna(subset=['order_id','customer_id'])
#dropping null values for order id and customer id

In [21]:
df1=df1.drop_duplicates(subset=['order_id'])
#dropping any duplicates for the order id so while creating relationship in sql we dont 
#get any erros or false relationship

In [22]:
df1.head()

,type,days_for_shipping_(real),days_for_shipment_(scheduled),benefit_per_order,sales_per_customer,delivery_status,late_delivery_risk,category_id,category_name,customer_city,...,order_zipcode,product_card_id,product_category_id,product_description,product_image,product_name,product_price,product_status,shipping_date_(dateorders),shipping_mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2/3/2018 22:56,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 11:24,Standard Class

In [23]:
df1=df1.rename(columns={"shipping_date_(dateorders)":"shipping_date"})
#rename columns

In [24]:
df1["shipping_date"]=pd.to_datetime(df1["shipping_date"],errors='coerce')
#changing the dtype of shipping date so we can use in sql smoothly

In [25]:
df1.head(5)

,type,days_for_shipping_(real),days_for_shipment_(scheduled),benefit_per_order,sales_per_customer,delivery_status,late_delivery_risk,category_id,category_name,customer_city,...,order_zipcode,product_card_id,product_category_id,product_description,product_image,product_name,product_price,product_status,shipping_date,shipping_mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2018-02-03 22:56:00,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2018-01-18 12:27:00,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2018-01-17 12:06:00,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2018-01-16 11:45:00,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2018-01-15 11:24:00,Standard Class

In [26]:
for col in df1.columns:
    print(col,":",df1[col].dtype)

#check the dtype of all the col and change for the one we need

type : object
days_for_shipping_(real) : int64
days_for_shipment_(scheduled) : int64
benefit_per_order : float64
sales_per_customer : float64
delivery_status : object
late_delivery_risk : int64
category_id : int64
category_name : object
customer_city : object
customer_country : object
customer_email : object
customer_fname : object
customer_id : int64
customer_lname : object
customer_password : object
customer_segment : object
customer_state : object
customer_street : object
customer_zipcode : float64
department_id : int64
department_name : object
latitude : float64
longitude : float64
market : object
order_city : object
order_country : object
order_customer_id : int64
order_date_(dateorders) : object
order_id : int64
order_item_cardprod_id : int64
order_item_discount : float64
order_item_discount_rate : float64
order_item_id : int64
order_item_product_price : float64
order_item_profit_ratio : float64
order_item_quantity : int64
sales : float64
order_item_total : float64
order_profit_per_order : float64
order_region : object
order_state : object
order_status : object
order_zipcode : float64
product_card_id : int64
product_category_id : int64
product_description : float64
product_image : object
product_name : object
product_price : float64
product_status : int64
shipping_date : datetime64[ns]
shipping_mode : object

In [27]:
df1=df1.rename(columns={'days_for_shipping_(real)':"days_for_shipping",
'days_for_shipment_(scheduled)':"days_for_shipment",'order_date_(dateorders)':"order_date"})

In [28]:
df1['order_date']=pd.to_datetime(df1['order_date'], errors='coerce')

In [29]:
df1['customer_zipcode']=df1['customer_zipcode'].astype('Int64')
df1['order_zipcode']=df1['order_zipcode'].astype('Int64')

In [30]:
df1=df1.drop(columns=['product_description'])
#since we have fixed most data types in the Supply_chain_dataset

In [31]:
#MOVING TO NEXT DATASET
df.head()

,Product,Category,Date,Month,Hour,Department,ip,url
0,adidas Brazuca 2017 Official Match Ball,baseball & softball,9/1/2017 6:00,Sep,6,fitness,37.97.182.65,/department/fitness/category/baseball%20&%20so...
1,The North Face Women's Recon Backpack,hunting & shooting,9/1/2017 6:00,Sep,6,fan shop,206.56.112.1,/department/fan%20shop/category/hunting%20&%20...
2,adidas Kids' RG III Mid Football Cleat,featured shops,9/1/2017 6:00,Sep,6,apparel,215.143.180.0,/department/apparel/category/featured%20shops/...
3,Under Armour Men's Compression EV SL Slide,electronics,9/1/2017 6:00,Sep,6,footwear,206.56.112.1,/department/footwear/category/electronics/prod...
4,Pelican Sunstream 100 Kayak,water sports,9/1/2017 6:01,Sep,6,fan shop,136.108.56.242,/department/fan%20shop/category/water%20sports...

In [32]:
for col in df.columns:
    print(col,":",df[col].dtype)

Product : object
Category : object
Date : object
Month : object
Hour : int64
Department : object
ip : object
url : object

In [33]:
df['Date']=pd.to_datetime(df['Date'],errors='coerce')

In [34]:
df.isna().sum()

Product       0
Category      0
Date          0
Month         0
Hour          0
Department    0
ip            0
url           0
dtype: int64

In [35]:
#from the above command we can conclude that the dataset is clean of null values
#The hidden trap for NaN values
(df == "").sum()

Product       0
Category      0
Date          0
Month         0
Hour          0
Department    0
ip            0
url           0
dtype: int64

In [36]:
for col in df.columns:
    null_count=df[col].isna().sum()
    print(f"{col}:{null_count} nulls")

Product:0 nulls
Category:0 nulls
Date:0 nulls
Month:0 nulls
Hour:0 nulls
Department:0 nulls
ip:0 nulls
url:0 nulls

In [37]:
df.info()
df.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 469977 entries, 0 to 469976
Data columns (total 8 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   Product     469977 non-null  object
 1   Category    469977 non-null  object
 2   Date        469977 non-null  datetime64[ns]
 3   Month       469977 non-null  object
 4   Hour        469977 non-null  int64
 5   Department  469977 non-null  object
 6   ip          469977 non-null  object
 7   url         469977 non-null  object
dtypes: datetime64[ns](1), int64(1), object(6)
memory usage: 28.7+ MB

(469977, 8)

In [38]:
#since the dataset is clean and doesnt have NaN we shall move to the last dataset
#before we start doing the table creation and view creation in sql
df2.head(5)

,FIELDS,DESCRIPTION
0,Type,: Type of transaction made
1,Days for shipping (real),: Actual shipping days of the purchased product
2,Days for shipment (scheduled),: Days of scheduled delivery of the purchased...
3,Benefit per order,: Earnings per order placed
4,Sales per customer,: Total sales per customer made per customer

In [39]:
for col in df2.columns:
    print(col,":",df2[col].dtype)

FIELDS : object
DESCRIPTION : object

In [40]:
df2.isna().sum()

FIELDS         0
DESCRIPTION    0
dtype: int64

In [41]:
df2=pd.read_csv("/kaggle/input/datasets/shashwatwork/dataco-smart-supply-chain-for-big-data-analysis/DescriptionDataCoSupplyChain.csv")

In [42]:
df2.head(5)

,FIELDS,DESCRIPTION
0,Type,: Type of transaction made
1,Days for shipping (real),: Actual shipping days of the purchased product
2,Days for shipment (scheduled),: Days of scheduled delivery of the purchased...
3,Benefit per order,: Earnings per order placed
4,Sales per customer,: Total sales per customer made per customer

In [43]:
df2.columns=df2.columns.str.lower()
df2.head(5)

,fields,description
0,Type,: Type of transaction made
1,Days for shipping (real),: Actual shipping days of the purchased product
2,Days for shipment (scheduled),: Days of scheduled delivery of the purchased...
3,Benefit per order,: Earnings per order placed
4,Sales per customer,: Total sales per customer made per customer

In [44]:
df2['description'] = df2['description'].str.replace(':', '', regex=False)
df2['fields']=df2['fields'].str.replace(r'[()]','',regex=True)
df2.head(5)

,fields,description
0,Type,Type of transaction made
1,Days for shipping real,Actual shipping days of the purchased product
2,Days for shipment scheduled,Days of scheduled delivery of the purchased ...
3,Benefit per order,Earnings per order placed
4,Sales per customer,Total sales per customer made per customer

In [45]:
df.head(5)

,Product,Category,Date,Month,Hour,Department,ip,url
0,adidas Brazuca 2017 Official Match Ball,baseball & softball,2017-09-01 06:00:00,Sep,6,fitness,37.97.182.65,/department/fitness/category/baseball%20&%20so...
1,The North Face Women's Recon Backpack,hunting & shooting,2017-09-01 06:00:00,Sep,6,fan shop,206.56.112.1,/department/fan%20shop/category/hunting%20&%20...
2,adidas Kids' RG III Mid Football Cleat,featured shops,2017-09-01 06:00:00,Sep,6,apparel,215.143.180.0,/department/apparel/category/featured%20shops/...
3,Under Armour Men's Compression EV SL Slide,electronics,2017-09-01 06:00:00,Sep,6,footwear,206.56.112.1,/department/footwear/category/electronics/prod...
4,Pelican Sunstream 100 Kayak,water sports,2017-09-01 06:01:00,Sep,6,fan shop,136.108.56.242,/department/fan%20shop/category/water%20sports...

In [46]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 65752 entries, 0 to 180490
Data columns (total 52 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   type                      65752 non-null  object
 1   days_for_shipping         65752 non-null  int64
 2   days_for_shipment         65752 non-null  int64
 3   benefit_per_order         65752 non-null  float64
 4   sales_per_customer        65752 non-null  float64
 5   delivery_status           65752 non-null  object
 6   late_delivery_risk        65752 non-null  int64
 7   category_id               65752 non-null  int64
 8   category_name             65752 non-null  object
 9   customer_city             65752 non-null  object
 10  customer_country          65752 non-null  object
 11  customer_email            65752 non-null  object
 12  customer_fname            65752 non-null  object
 13  customer_id               65752 non-null  int64
 14  customer_lname            65744 non-null  object
 15  customer_password         65752 non-null  object
 16  customer_segment          65752 non-null  object
 17  customer_state            65752 non-null  object
 18  customer_street           65752 non-null  object
 19  customer_zipcode          65749 non-null  Int64
 20  department_id             65752 non-null  int64
 21  department_name           65752 non-null  object
 22  latitude                  65752 non-null  float64
 23  longitude                 65752 non-null  float64
 24  market                    65752 non-null  object
 25  order_city                65752 non-null  object
 26  order_country             65752 non-null  object
 27  order_customer_id         65752 non-null  int64
 28  order_date                65752 non-null  datetime64[ns]
 29  order_id                  65752 non-null  int64
 30  order_item_cardprod_id    65752 non-null  int64
 31  order_item_discount       65752 non-null  float64
 32  order_item_discount_rate  65752 non-null  float64
 33  order_item_id             65752 non-null  int64
 34  order_item_product_price  65752 non-null  float64
 35  order_item_profit_ratio   65752 non-null  float64
 36  order_item_quantity       65752 non-null  int64
 37  sales                     65752 non-null  float64
 38  order_item_total          65752 non-null  float64
 39  order_profit_per_order    65752 non-null  float64
 40  order_region              65752 non-null  object
 41  order_state               65752 non-null  object
 42  order_status              65752 non-null  object
 43  order_zipcode             8270 non-null   Int64
 44  product_card_id           65752 non-null  int64
 45  product_category_id       65752 non-null  int64
 46  product_image             65752 non-null  object
 47  product_name              65752 non-null  object
 48  product_price             65752 non-null  float64
 49  product_status            65752 non-null  int64
 50  shipping_date             65752 non-null  datetime64[ns]
 51  shipping_mode             65752 non-null  object
dtypes: Int64(2), datetime64[ns](2), float64(12), int64(14), object(22)
memory usage: 26.7+ MB

In [47]:
from sqlalchemy import create_engine
from kaggle_secrets import UserSecretsClient

# 1. Fetch your connection string securely from Kaggle Secrets
user_secrets = UserSecretsClient()
db_url = user_secrets.get_secret("DB_URL")

# Ensure standard SQLAlchemy driver prefix
if db_url.startswith("postgres://"):
    db_url = db_url.replace("postgres://", "postgresql://", 1)

# 2. Create the engine and push the DataFrame to Neon PostgreSQL
engine = create_engine(db_url)

print("Connecting to Neon PostgreSQL...")

Connecting to Neon PostgreSQL...

In [48]:
#splittin the main csv into four different tables
dim_customers=df1[['customer_id','customer_fname','customer_lname','customer_segment',
                   'customer_email','customer_password','customer_street','customer_zipcode','customer_city',
                   'customer_state','customer_country']].drop_duplicates(subset=['customer_id']).copy()

In [49]:
dim_products=df1[['product_card_id','product_category_id','product_name',
                 'product_price',
                  'category_id','category_name','department_id','department_name']
].drop_duplicates(subset=['product_card_id']).copy()

In [50]:
dim_logistics = df1[['shipping_mode',
                     'delivery_status', 
                     'late_delivery_risk',
                     'market', 'order_region']].drop_duplicates().reset_index(drop=True).copy()
#creating logistics id and giving it a index values
dim_logistics['logistics_id'] = dim_logistics.index + 1

In [51]:
orders_cols=[c for c in['order_item_id', 'order_id', 'customer_id', 'product_card_id', 'logistics_id',
                        'order_item_quantity', 'order_item_product_price', 'order_item_discount',
                        'order_item_discount_rate', 'order_item_total', 'order_item_profit_ratio',
                        'sales', 'sales_per_customer', 'benefit_per_order', 'order_profit_per_order']
            if c in df1.columns]
dim_orders_items=df1[orders_cols].drop_duplicates(subset=['order_item_id']).copy()

In [52]:
dim_orders=df1[['order_id', 'order_date', 'shipping_date', 'order_status', 
                  'type', 'market', 'order_region', 'order_country', 
                  'order_state', 'order_city', 'order_zipcode', 
                  'days_for_shipping', 'days_for_shipment']].drop_duplicates(subset=['order_id']).copy()
df1.head(5)

,type,days_for_shipping,days_for_shipment,benefit_per_order,sales_per_customer,delivery_status,late_delivery_risk,category_id,category_name,customer_city,...,order_status,order_zipcode,product_card_id,product_category_id,product_image,product_name,product_price,product_status,shipping_date,shipping_mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,COMPLETE,<NA>,1360,73,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2018-02-03 22:56:00,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,PENDING,<NA>,1360,73,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2018-01-18 12:27:00,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,CLOSED,<NA>,1360,73,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2018-01-17 12:06:00,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,COMPLETE,<NA>,1360,73,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2018-01-16 11:45:00,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,PENDING_PAYMENT,<NA>,1360,73,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2018-01-15 11:24:00,Standard Class

In [53]:
#merging table dim logistic with df1 raw table for the following columns using left merge
df1=df1.merge(dim_logistics,on=['shipping_mode',
                                'delivery_status','late_delivery_risk','market','order_region'],how='left')

In [54]:
#pushing the tables on the NEON db
print("pushing optimized tables on neon")
dim_customers.to_sql('dim_customers',con=engine,if_exists='replace',index=False)
dim_products.to_sql('dim_products',con=engine,if_exists='replace',index=False)
dim_logistics.to_sql('dim_logistics',con=engine,if_exists='replace',index=False)
print("pushed")

pushing optimized tables on neon
pushed

In [55]:
orders_items_cols = [
    "order_id",
    "customer_id",
    "product_card_id",
    "logistics_id",
    "order_item_quantity",
    "order_item_product_price",
    "order_item_discount",
    "order_item_discount_rate",
    "order_item_total",
    "order_item_profit_ratio",
    "sales",
    "sales_per_customer",
    "benefit_per_order",
    "order_profit_per_order"
]

dim_orders_items = df1[orders_items_cols].copy()

# Keep the existing row structure and create a unique item key
dim_orders_items["item_seq"] = (
    dim_orders_items.groupby("order_id").cumcount() + 1
)

dim_orders_items["order_item_key"] = (
    dim_orders_items["order_id"].astype(str)
    + "_"
    + dim_orders_items["item_seq"].astype(str)
)

dim_orders_items = dim_orders_items.drop(columns=["item_seq"])

In [56]:
print("Orders:", df1["order_id"].nunique())
print("Order item rows:", len(dim_orders_items))
print("Unique item keys:", dim_orders_items["order_item_key"].nunique())

Orders: 65752
Order item rows: 65752
Unique item keys: 65752

In [57]:
dim_orders = df1[
    [
        "order_id", "order_date", "shipping_date", "order_status", "type",
        "market", "order_region",
        "order_country", "order_state", "order_city", "order_zipcode",
        "days_for_shipping", "days_for_shipment"
    ]
].drop_duplicates(subset=["order_id"]).copy()

In [58]:
from sqlalchemy import create_engine, text
from kaggle_secrets import UserSecretsClient

user_secrets = UserSecretsClient()
db_url = user_secrets.get_secret("DB_URL")

if db_url.startswith("postgres://"):
    db_url = db_url.replace("postgres://", "postgresql://", 1)

engine = create_engine(
    db_url,
    pool_pre_ping=True,
    pool_recycle=300
)

print("New Neon engine created.")
with engine.connect() as conn:
    result = conn.execute(text("SELECT 1"))
    print(result.scalar())

print("Neon connection successful.")

New Neon engine created.
1
Neon connection successful.

In [59]:
from sqlalchemy import text

with engine.connect() as conn:
    conn.execute(text("DROP TABLE IF EXISTS dim_orders_items CASCADE;"))
    conn.execute(text("DROP TABLE IF EXISTS dim_orders CASCADE;"))
    conn.commit()

print("Old tables dropped.")

Old tables dropped.

In [60]:
print("Uploading dim_orders...")
dim_orders.to_sql("dim_orders", con=engine, if_exists="replace", index=False, chunksize=5000)
print("dim_orders uploaded.")

print("Uploading dim_orders_items...")
dim_orders_items.to_sql("dim_orders_items", con=engine, if_exists="replace", index=False, chunksize=5000)
print("dim_orders_items uploaded.")

Uploading dim_orders...
dim_orders uploaded.
Uploading dim_orders_items...
dim_orders_items uploaded.

In [61]:
from sqlalchemy import text

with engine.connect() as conn:
    # 1. Add primary key to dim_orders
    conn.execute(text("""
        ALTER TABLE dim_orders
        ADD CONSTRAINT pk_dim_orders PRIMARY KEY (order_id);
    """))
    conn.commit()

print("Primary key added to dim_orders.")

Primary key added to dim_orders.

In [62]:
with engine.connect() as conn:
    conn.execute(text("""
        ALTER TABLE dim_orders_items
        ADD CONSTRAINT fk_dim_order_items_orders
        FOREIGN KEY (order_id) REFERENCES dim_orders(order_id);
    """))
    conn.commit()

print("FK constraint restored.")

FK constraint restored.

In [63]:
tables = {
    "dim_customers": dim_customers,
    "dim_products": dim_products,
    "dim_logistics": dim_logistics,
    "dim_orders": dim_orders,
    "dim_orders_items": dim_orders_items
}

In [64]:
for name, df in tables.items():

    print("\n" + "=" * 60)
    print(name)
    print("=" * 60)

    print("Rows:", len(df))
    print("Columns:", len(df.columns))
    print("Duplicate rows:", df.duplicated().sum())
    print("Missing values:", df.isnull().sum().sum())

    print("\nColumns:")
    print(df.columns.tolist())

============================================================
dim_customers
============================================================
Rows: 20652
Columns: 11
Duplicate rows: 0
Missing values: 11

Columns:
['customer_id', 'customer_fname', 'customer_lname', 'customer_segment', 'customer_email', 'customer_password', 'customer_street', 'customer_zipcode', 'customer_city', 'customer_state', 'customer_country']

============================================================
dim_products
============================================================
Rows: 118
Columns: 8
Duplicate rows: 0
Missing values: 0

Columns:
['product_card_id', 'product_category_id', 'product_name', 'product_price', 'category_id', 'category_name', 'department_id', 'department_name']

============================================================
dim_logistics
============================================================
Rows: 273
Columns: 6
Duplicate rows: 0
Missing values: 0

Columns:
['shipping_mode', 'delivery_status', 'late_delivery_risk', 'market', 'order_region', 'logistics_id']

============================================================
dim_orders
============================================================
Rows: 65752
Columns: 13
Duplicate rows: 0
Missing values: 57482

Columns:
['order_id', 'order_date', 'shipping_date', 'order_status', 'type', 'market', 'order_region', 'order_country', 'order_state', 'order_city', 'order_zipcode', 'days_for_shipping', 'days_for_shipment']

============================================================
dim_orders_items
============================================================
Rows: 65752
Columns: 15
Duplicate rows: 0
Missing values: 0

Columns:
['order_id', 'customer_id', 'product_card_id', 'logistics_id', 'order_item_quantity', 'order_item_product_price', 'order_item_discount', 'order_item_discount_rate', 'order_item_total', 'order_item_profit_ratio', 'sales', 'sales_per_customer', 'benefit_per_order', 'order_profit_per_order', 'order_item_key']

In [65]:
print("\n--- PRIMARY KEY CHECKS ---")

print(
    "dim_customers:",
    dim_customers["customer_id"].nunique(),
    "unique /",
    len(dim_customers),
    "rows"
)

print(
    "dim_products:",
    dim_products["product_card_id"].nunique(),
    "unique /",
    len(dim_products),
    "rows"
)

print(
    "dim_logistics:",
    dim_logistics["logistics_id"].nunique(),
    "unique /",
    len(dim_logistics),
    "rows"
)

print(
    "dim_orders:",
    dim_orders["order_id"].nunique(),
    "unique /",
    len(dim_orders),
    "rows"
)

print(
    "dim_orders_items:",
    dim_orders_items["order_item_key"].nunique(),
    "unique /",
    len(dim_orders_items),
    "rows"
)

--- PRIMARY KEY CHECKS ---
dim_customers: 20652 unique / 20652 rows
dim_products: 118 unique / 118 rows
dim_logistics: 273 unique / 273 rows
dim_orders: 65752 unique / 65752 rows
dim_orders_items: 65752 unique / 65752 rows

In [66]:
df1.head(5)

,type,days_for_shipping,days_for_shipment,benefit_per_order,sales_per_customer,delivery_status,late_delivery_risk,category_id,category_name,customer_city,...,order_zipcode,product_card_id,product_category_id,product_image,product_name,product_price,product_status,shipping_date,shipping_mode,logistics_id
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,<NA>,1360,73,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2018-02-03 22:56:00,Standard Class,1
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,<NA>,1360,73,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2018-01-18 12:27:00,Standard Class,2
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,<NA>,1360,73,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2018-01-17 12:06:00,Standard Class,3
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,<NA>,1360,73,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2018-01-16 11:45:00,Standard Class,4
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,<NA>,1360,73,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2018-01-15 11:24:00,Standard Class,4